# Generated by Django 4.2.14 on 2024-11-03 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='images/defaultAvatar.png', max_length=255, verbose_name='image'),
        ),
    ]
