# Generated by Django 4.2.14 on 2024-10-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_doctor'),
        ('patientSummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsummary',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='appointment.appointment'),
        ),
    ]
