# Generated by Django 4.2.14 on 2024-11-03 06:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/defaultAvatar.png', max_length=255, verbose_name='image'),
        ),
    ]
